package com.sellphones.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
public enum ErrorCode {
    NEED_RELOGIN("Vui lòng đăng xuất và đăng nhập lại người dùng trước khi thực hiện thao tác này", HttpStatus.BAD_REQUEST),
    VARIANT_NOT_IN_INVENTORY("Biến thể sản phẩm không tồn tại trong inventory tương ứng", HttpStatus.BAD_REQUEST),
    INVENTORY_QUANTITY_CANNOT_BE_NEGATIVE("Số lượng của inventory không thể âm", HttpStatus.BAD_REQUEST),
    ROLE_IN_USE("Vai trò này đang được sử dụng bởi người dùng khác", HttpStatus.BAD_REQUEST),
    VARIANT_INACTIVE("Phiên bản hiện đang ngừng hoạt động", HttpStatus.BAD_REQUEST),
    PRODUCT_INACTIVE("Sản phẩm hiện đang ngừng hoạt động", HttpStatus.BAD_REQUEST),
    PRODUCT_NOT_FOUND("Không tìm thấy sản phẩm", HttpStatus.NOT_FOUND),
    MOST_SELLING_VARIANT_NOT_FOUND("Không tìm thấy sản phẩm bán chạy", HttpStatus.NOT_FOUND),
    CART_EMPTY("Giỏ hàng trống, không thể tạo đơn hàng", HttpStatus.BAD_REQUEST),
    PRODUCT_VARIANT_NOT_FOUND("Không tìm thấy biến thể sản phẩm", HttpStatus.NOT_FOUND),
    PRODUCT_VARIANT_ID_NULL_EXCEPTION("ID biến thể sản phẩm bị trống", HttpStatus.BAD_REQUEST),
    USER_NOT_FOUND("Không tìm thấy người dùng", HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD("Sai mật khẩu", HttpStatus.UNAUTHORIZED),
    GOOGLE_ACCOUNT_NO_PASSWORD("Tài khoản này được tạo bằng Google. Vui lòng sử dụng chức năng quên mật khẩu để đặt mật khẩu.", HttpStatus.BAD_REQUEST),
    TOKEN_EXPIRED("Token đã hết hạn", HttpStatus.UNAUTHORIZED),
    REDIRECT_FAILED("Không thể chuyển hướng sau khi thanh toán", HttpStatus.INTERNAL_SERVER_ERROR),
    PAYMENT_ALREADY_COMPLETED("Thanh toán này đã được thực hiện", HttpStatus.BAD_REQUEST),
    TOKEN_PARSE_ERROR("Lỗi phân tích token", HttpStatus.UNAUTHORIZED),
    TOKEN_GENERATION_FAILED("Không thể tạo token", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_VNPAY_SIGNATURE("Chữ ký VNPAY không hợp lệ", HttpStatus.BAD_REQUEST),
    GET_AUTHENTICATION_MANAGER_FAILED("Không thể lấy trình quản lý xác thực", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_AUTHORIZATION_HEADER("Header xác thực không hợp lệ", HttpStatus.UNAUTHORIZED),
    CART_ITEM_ALREADY_EXISTS("Sản phẩm đã tồn tại trong giỏ hàng", HttpStatus.CONFLICT),
    CART_ITEM_NOT_FOUND("Không tìm thấy sản phẩm trong giỏ hàng", HttpStatus.NOT_FOUND),
    ROLE_NOT_FOUND("Không tìm thấy vai trò", HttpStatus.NOT_FOUND),
    ATTRIBUTE_NAME_ALREADY_EXISTS( "Tên thuộc tính đã tồn tại", HttpStatus.CONFLICT),
    CATEGORY_NAME_ALREADY_EXISTS("Tên danh mục đã tồn tại", HttpStatus.CONFLICT),
    CATEGORY_CODE_ALREADY_EXISTS("Mã danh mục đã tồn tại", HttpStatus.CONFLICT),
    DATABASE_ERROR("Lỗi cơ sở dữ liệu", HttpStatus.INTERNAL_SERVER_ERROR),
    PAYMENT_METHOD_TYPE_NOT_FOUND("Không tìm thấy loại phương thức thanh toán", HttpStatus.NOT_FOUND),
    PAYMENT_METHOD_NOT_FOUND("Không tìm thấy phương thức thanh toán", HttpStatus.NOT_FOUND),
    ORDER_NOT_FOUND("Không tìm thấy đơn hàng", HttpStatus.NOT_FOUND),
    ATTRIBUTE_NOT_FOUND("Không tìm thấy thuộc tính", HttpStatus.NOT_FOUND),
    ATTRIBUTE_VALUE_NOT_FOUND("Không tìm thấy giá trị thuộc tính", HttpStatus.NOT_FOUND),
    CATEGORY_OPTION_NOT_FOUND("Không tìm thấy tùy chọn danh mục", HttpStatus.NOT_FOUND),
    CATEGORY_OPTION_VALUE_NOT_FOUND("Không tìm thấy giá trị tùy chọn danh mục", HttpStatus.NOT_FOUND),
    CATEGORY_NOT_FOUND("Không tìm thấy danh mục", HttpStatus.NOT_FOUND),
    REVIEW_NOT_FOUND("Không tìm thấy đánh giá", HttpStatus.NOT_FOUND),
    COMMENT_NOT_FOUND("Không tìm thấy bình luận", HttpStatus.NOT_FOUND),
    BRAND_NOT_FOUND("Không tìm thấy thương hiệu", HttpStatus.NOT_FOUND),
    ADDRESS_NOT_FOUND("Không tìm thấy địa chỉ", HttpStatus.NOT_FOUND),
    CUSTOMER_NOT_FOUND("Không tìm thấy khách hàng", HttpStatus.NOT_FOUND),
    SUPPLIER_NOT_FOUND("Không tìm thấy nhà cung cấp", HttpStatus.NOT_FOUND),
    PRODUCT_FILTER_NOT_FOUND("Không tìm thấy bộ lọc sản phẩm", HttpStatus.NOT_FOUND),
    PROMOTION_BANNER_NOT_FOUND("Không tìm thấy banner khuyến mãi", HttpStatus.NOT_FOUND),
    STOCK_ENTRY_NOT_FOUND("Không tìm thấy phiếu nhập kho", HttpStatus.NOT_FOUND),
    INVALID_LOGIN_METHOD("Phương thức đăng nhập không hợp lệ. Vui lòng sử dụng tùy chọn đăng nhập đúng.", HttpStatus.BAD_REQUEST),
    INVENTORY_NOT_FOUND("Không tìm thấy hàng tồn kho", HttpStatus.NOT_FOUND),
    WAREHOUSE_NOT_FOUND("Không tìm thấy kho hàng", HttpStatus.NOT_FOUND),
    WARRANTY_NOT_FOUND("Không tìm thấy thông tin bảo hành", HttpStatus.NOT_FOUND),
    SHIPMENT_NOT_FOUND("Không tìm thấy thông tin giao hàng", HttpStatus.NOT_FOUND),
    PAYMENT_NOT_FOUND("Không tìm thấy thông tin thanh toán", HttpStatus.NOT_FOUND),
    FILTER_OPTION_NOT_FOUND("Không tìm thấy tùy chọn lọc", HttpStatus.NOT_FOUND),
    GIFT_PRODUCT_NOT_FOUND("Không tìm thấy sản phẩm quà tặng", HttpStatus.NOT_FOUND),
    PRODUCT_PROMOTION_NOT_FOUND("Không tìm thấy khuyến mãi sản phẩm", HttpStatus.NOT_FOUND),
    CANNOT_DELETE_CUSTOMER_ADDRESS("Không thể xóa địa chỉ thuộc loại 'CUSTOMER'", HttpStatus.BAD_REQUEST),
    PRODUCT_PROMOTION_NOT_FOUND_IN_PRODUCT("Không tìm thấy khuyến mãi trong sản phẩm", HttpStatus.NOT_FOUND),
    WARRANTY_NOT_FOUND_IN_PRODUCT("Không tìm thấy bảo hành trong sản phẩm", HttpStatus.NOT_FOUND),
    PRODUCT_VARIANT_OUT_OF_STOCK("Phiên bản này đã hết hàng", HttpStatus.BAD_REQUEST),
    INVALID_PROMOTION_CONFIG("Cấu hình khuyến mãi không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_SHIPMENT_ITEMS("Danh sách sản phẩm giao hàng không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_REQUEST_FORMAT("Định dạng yêu cầu không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_CONDITION("Điều kiện không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_REVIEW_REQUEST_FORMAT("Định dạng yêu cầu đánh giá không hợp lệ", HttpStatus.BAD_REQUEST),
    INVENTORY_ALREADY_EXISTS("Hàng tồn kho đã tồn tại cho biến thể và kho hàng này", HttpStatus.CONFLICT),
    WAREHOUSE_ALREADY_EXISTS("Kho hàng đã tồn tại cho địa chỉ này", HttpStatus.CONFLICT),
    INVALID_BRAND_REQUEST_FORMAT("Định dạng yêu cầu thương hiệu không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_PRODUCT_REQUEST_FORMAT("Định dạng yêu cầu sản phẩm không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_ACTIVE_TOKEN("Token kích hoạt không hợp lệ", HttpStatus.UNAUTHORIZED),
    INVALID_ROLE("Vai trò không hợp lệ", HttpStatus.UNAUTHORIZED),
    USER_INACTIVE("Người dùng chưa được kích hoạt", HttpStatus.BAD_REQUEST),
    USER_HAS_NOT_PURCHASED("Người dùng chưa mua sản phẩm", HttpStatus.BAD_REQUEST),
    NOT_CUSTOMER("Người dùng không được phép đăng nhập với vai trò khách hàng", HttpStatus.FORBIDDEN),
    EMPTY_FILE("Tệp rỗng", HttpStatus.BAD_REQUEST),
    INVALID_OTP("Mã OTP không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_RESET_TOKEN("Mã OTP đặt lại mật khẩu không hợp lệ", HttpStatus.BAD_REQUEST),
    CANNOT_STORE_FILE_OUTSIDE_CURRENT_DIRECTORY("Không thể lưu tệp bên ngoài thư mục hiện tại", HttpStatus.BAD_REQUEST),
    CANNOT_READ_FILE_OUTSIDE_CURRENT_DIRECTORY("Không thể đọc tệp bên ngoài thư mục hiện tại", HttpStatus.BAD_REQUEST),
    CANCEL_ORDER_FAILED("Hủy đơn hàng thất bại", HttpStatus.BAD_REQUEST),
    INVALID_ATTRIBUTE_ID("ID thuộc tính không hợp lệ", HttpStatus.BAD_REQUEST),
    CANNOT_READ_FILE("Không thể đọc tệp", HttpStatus.BAD_REQUEST),
    FILE_UPLOAD_FAILED("Tải tệp lên thất bại", HttpStatus.BAD_REQUEST),
    INVALID_RESET_PASSWORD_TOKEN("Token đặt lại mật khẩu không hợp lệ", HttpStatus.BAD_REQUEST),
    USER_NOT_FOUND_FOR_ACTIVE_TOKEN("Không tìm thấy người dùng tương ứng với token kích hoạt", HttpStatus.NOT_FOUND),
    OTP_NOT_FOUND_FOR_EMAIL("Không tìm thấy OTP cho email đã cung cấp", HttpStatus.NOT_FOUND),
    TIME_LIMIT_NOT_REACHED("Yêu cầu OTP quá sớm. Vui lòng đợi ít nhất 60 giây trước khi thử lại", HttpStatus.BAD_REQUEST),
    USER_ALREADY_EXISTS("Tên email đã tồn tại", HttpStatus.CONFLICT),
    CART_NOT_FOUND("Không tìm thấy giỏ hàng", HttpStatus.NOT_FOUND),
    UNAUTHORIZED_ADMIN_ACCESS("Bạn không có quyền truy cập tài nguyên của quản trị viên", HttpStatus.FORBIDDEN),
    UNAUTHORIZED_CUSTOMER_ACCESS("Bạn không có quyền truy cập tài nguyên của khách hàng", HttpStatus.FORBIDDEN),
    INVALID_STATUS_TRANSITION("Chuyển trạng thái đơn hàng không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_TOKEN("Token không hợp lệ", HttpStatus.UNAUTHORIZED);

    private String message;
    private HttpStatusCode statusCode;

    ErrorCode(String message, HttpStatusCode statusCode) {
        this.message = message;
        this.statusCode = statusCode;
    }

}
